version: "3"

tasks:
  protoc:
    cmds:
      - echo "Generating protobuf"
      - protoc --go_out=./ ./public/retro.proto
  server:
    cmds:
      - echo "Building server"
      - go build -o server.out ./cmd/server
  client:
    cmds:
      - echo "Building client"
      - go build -o client.out ./cmd/client
