version: "3"

tasks:
  build-front:
    cmds:
      - echo "Building front"
      - cd front && npm run build
      - mkdir -p public
      - cp -r front/dist/* public/
  protoc:
    cmds:
      - echo "Generating protobuf"
      - protoc --go_out=./ --plugin=./front/node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./front/src/ ./retro.proto
  server:
    cmds:
      - echo "Building server"
      - go build -o server.out ./cmd/server
